/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g11_pfbomberos.Vistas;

/**
 *
 * @author SCP-062
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorioMain = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jInfoCuartel = new javax.swing.JMenu();
        jItemCuartel = new javax.swing.JMenuItem();
        jBomBrigadas = new javax.swing.JMenu();
        jMguardarBrig = new javax.swing.JMenuItem();
        jItemBrigradas = new javax.swing.JMenuItem();
        jEmergenciasAct = new javax.swing.JMenu();
        jItemEmerAct = new javax.swing.JMenuItem();
        jEmergenciasPas = new javax.swing.JMenu();
        jItemEmerRes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioMainLayout = new javax.swing.GroupLayout(escritorioMain);
        escritorioMain.setLayout(escritorioMainLayout);
        escritorioMainLayout.setHorizontalGroup(
            escritorioMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );
        escritorioMainLayout.setVerticalGroup(
            escritorioMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        jInfoCuartel.setText("Cuartel");
        jInfoCuartel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInfoCuartelActionPerformed(evt);
            }
        });

        jItemCuartel.setText("Info Cuartel");
        jItemCuartel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemCuartelActionPerformed(evt);
            }
        });
        jInfoCuartel.add(jItemCuartel);

        jMenuBar1.add(jInfoCuartel);

        jBomBrigadas.setText("Brigadas");

        jMguardarBrig.setText("Guardar Brigada");
        jMguardarBrig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMguardarBrigActionPerformed(evt);
            }
        });
        jBomBrigadas.add(jMguardarBrig);

        jItemBrigradas.setText("Ver Brigadas");
        jItemBrigradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemBrigradasActionPerformed(evt);
            }
        });
        jBomBrigadas.add(jItemBrigradas);

        jMenuBar1.add(jBomBrigadas);

        jEmergenciasAct.setText("Emergencias Actuales");

        jItemEmerAct.setText("Ver Emergencias");
        jItemEmerAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemEmerActActionPerformed(evt);
            }
        });
        jEmergenciasAct.add(jItemEmerAct);

        jMenuBar1.add(jEmergenciasAct);

        jEmergenciasPas.setText("Emergencias Resueltas");

        jItemEmerRes.setText("Ver Emergencias Resueltas");
        jItemEmerRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemEmerResActionPerformed(evt);
            }
        });
        jEmergenciasPas.add(jItemEmerRes);

        jMenuBar1.add(jEmergenciasPas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jInfoCuartelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInfoCuartelActionPerformed
        
    }//GEN-LAST:event_jInfoCuartelActionPerformed

    private void jItemCuartelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemCuartelActionPerformed
        escritorioMain.removeAll();
        escritorioMain.repaint();
        Cuartel_view cuartelView = new Cuartel_view();
        cuartelView.setVisible(true);
        escritorioMain.add(cuartelView);
    }//GEN-LAST:event_jItemCuartelActionPerformed

    private void jItemBrigradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemBrigradasActionPerformed
        escritorioMain.removeAll();
        escritorioMain.repaint();
        MostrarBrigada brigadaView = new MostrarBrigada();
        brigadaView.setVisible(true);
        escritorioMain.add(brigadaView);
    }//GEN-LAST:event_jItemBrigradasActionPerformed

    private void jItemEmerActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemEmerActActionPerformed
        escritorioMain.removeAll();
        escritorioMain.repaint();
        Emergencias_actuales_view emeractView = new Emergencias_actuales_view();
        emeractView.setVisible(true);
        escritorioMain.add(emeractView);
    }//GEN-LAST:event_jItemEmerActActionPerformed

    private void jItemEmerResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemEmerResActionPerformed
        escritorioMain.removeAll();
        escritorioMain.repaint();
        Emergencias_resueltas_view emerresView = new Emergencias_resueltas_view();
        emerresView.setVisible(true);
        escritorioMain.add(emerresView);
    }//GEN-LAST:event_jItemEmerResActionPerformed

    private void jMguardarBrigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMguardarBrigActionPerformed
       escritorioMain.removeAll();
        escritorioMain.repaint();
        GuardarBrigada modificarView = new GuardarBrigada();
        modificarView.setVisible(true);
        escritorioMain.add(modificarView);
    }//GEN-LAST:event_jMguardarBrigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorioMain;
    private javax.swing.JMenu jBomBrigadas;
    private javax.swing.JMenu jEmergenciasAct;
    private javax.swing.JMenu jEmergenciasPas;
    private javax.swing.JMenu jInfoCuartel;
    private javax.swing.JMenuItem jItemBrigradas;
    private javax.swing.JMenuItem jItemCuartel;
    private javax.swing.JMenuItem jItemEmerAct;
    private javax.swing.JMenuItem jItemEmerRes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMguardarBrig;
    // End of variables declaration//GEN-END:variables
}
